### ISSUE TITLE
Keep block under player from fading

### ISSUE THREAD

**Issue by u0398** [Timefall-Development/FadingClouds#1]
Currently the cloud block under the player slowly fades, and then reappears in a continuous cycle. Would it be possible to keep that from occurring?

P.S. Great little mod. Hope it gets a lot of attention!

**Comment by Yurpio** [comment]
@u0398 just fixed this, there is now a gamerule to switch between the new and old system :)
Issue closed with https://github.com/Timefall-Development/FadingClouds/commit/e1065a5857350fd8a0a359a59e61d7327a88a695
