### ISSUE TITLE
Way to disable fading blocks

### ISSUE THREAD

**Issue by u0398** [Timefall-Development/FadingClouds#3]
It would be nice if players had a way to disable new fading block creation while still wearing Cloud Walker trimmed boots.

Maybe a key bind.

**Comment by Yurpio** [comment]
actually you can, if you hold the crouch button, but i should probably put that somewhere in the mod description...

**Comment by u0398** [comment]
I meant something that allows normal movement, using an elytra, etc. without crouching.
